// Generated from src/telegram/taskKinds.ts. Run npm run generate:runtime.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TELEGRAM_TASK_KINDS =
  exports.TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND =
  exports.TELEGRAM_PENDING_DELETE_TASK_KIND =
  exports.TELEGRAM_MANUAL_RECOVERY_TASK_KIND =
  exports.TELEGRAM_DESIRED_TASK_KIND =
    void 0;
const TELEGRAM_DESIRED_TASK_KIND = "desired";
exports.TELEGRAM_DESIRED_TASK_KIND = TELEGRAM_DESIRED_TASK_KIND;
const TELEGRAM_MANUAL_RECOVERY_TASK_KIND = "manual-recovery";
exports.TELEGRAM_MANUAL_RECOVERY_TASK_KIND = TELEGRAM_MANUAL_RECOVERY_TASK_KIND;
const TELEGRAM_PENDING_DELETE_TASK_KIND = "pending-delete";
exports.TELEGRAM_PENDING_DELETE_TASK_KIND = TELEGRAM_PENDING_DELETE_TASK_KIND;
const TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND = "rate-limit-proof";
exports.TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND =
  TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND;
const TELEGRAM_TASK_KINDS = new Set([
  TELEGRAM_DESIRED_TASK_KIND,
  TELEGRAM_MANUAL_RECOVERY_TASK_KIND,
  TELEGRAM_PENDING_DELETE_TASK_KIND,
  TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND,
]);
exports.TELEGRAM_TASK_KINDS = TELEGRAM_TASK_KINDS;
