"use strict";

const TELEGRAM_DESIRED_TASK_KIND = "desired";
const TELEGRAM_MANUAL_RECOVERY_TASK_KIND = "manual-recovery";
const TELEGRAM_PENDING_DELETE_TASK_KIND = "pending-delete";
const TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND = "rate-limit-proof";
const TELEGRAM_TASK_KINDS = new Set([
  TELEGRAM_DESIRED_TASK_KIND,
  TELEGRAM_MANUAL_RECOVERY_TASK_KIND,
  TELEGRAM_PENDING_DELETE_TASK_KIND,
  TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND,
]);

module.exports = {
  TELEGRAM_DESIRED_TASK_KIND,
  TELEGRAM_MANUAL_RECOVERY_TASK_KIND,
  TELEGRAM_PENDING_DELETE_TASK_KIND,
  TELEGRAM_RATE_LIMIT_PROOF_TASK_KIND,
  TELEGRAM_TASK_KINDS,
};
